# Generated by Django 4.0.2 on 2024-03-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.collections'),
        ),
    ]
