# Generated by Django 4.0.2 on 2024-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(default=None, null=True, related_name='item', to='item.Collections'),
        ),
    ]
