# Generated by Django 4.0.2 on 2024-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
