# Generated by Django 4.0.2 on 2024-08-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
